---
title: "Hands-on Exercise - Descriptive (Univariate) Stats"
---

## Lesson 06: Descriptive (Univariate) Stats

This lesson focuses on describing and summarizing data using univariate stats. We will be working with the H.E.L.P. dataset.

## The HELP Dataset 

For today and several future lessons, we'll be working with the HELP (Health Evaluation and Linkage to Primary Care) dataset. You can learn more about this dataset at [https://nhorton.people.amherst.edu/sasr2/datasets.php](https://nhorton.people.amherst.edu/sasr2/datasets.php). This dataset is also used by Ken Kleinman and Nicholas J. Horton for their book "SAS and R: Data Management, Statistical Analysis, and Graphics" _(which is another helpful textbook)_.

* You can download the datasets from their website [https://nhorton.people.amherst.edu/sasr2/datasets.php](https://nhorton.people.amherst.edu/sasr2/datasets.php)
* The original publication is referenced at [https://www.ncbi.nlm.nih.gov/pubmed/12653820?ordinalpos=17&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DefaultReportPanel.Pubmed_RVDocSum](https://www.ncbi.nlm.nih.gov/pubmed/12653820?ordinalpos=17&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DefaultReportPanel.Pubmed_RVDocSum)
* The HELP documentation (including all forms/surveys/instruments used) are located at [https://nhorton.people.amherst.edu/help/](https://nhorton.people.amherst.edu/help/)
    - specifically the details on all BASELINE assessments are located in this PDF [https://nhorton.people.amherst.edu/help/HELP-baseline.pdf](https://nhorton.people.amherst.edu/help/HELP-baseline.pdf)
    - with the follow up time points described in the PDF [https://nhorton.people.amherst.edu/help/HELP-followup.pdf](https://nhorton.people.amherst.edu/help/HELP-followup.pdf)
    
* See details on the HELP dataset at [https://melindahiggins2000.github.io/N736Fall2017_HELPdataset/](https://melindahiggins2000.github.io/N736Fall2017_HELPdataset/)

## Download the HELP Dataset

* Data in `SAS7BDAT` format [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sas7bdat](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sas7bdat)
* Formats in `SAS7BDAT` format [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/formats.sas7bcat](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/formats.sas7bcat)
* `SPSS` format [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sav](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sav)
* `.RData` format [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.RData](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.RData)


## Getting Started with HELP Dataset

* `R` Scripts
    - R Script to load HELP dataset [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/loadHELPdata.R](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/loadHELPdata.R)
    - R Script for beginning univariate analyses [https://github.com/melindahiggins2000/N736Fall2017_lesson07/raw/master/lesson07_Rcode.R](https://github.com/melindahiggins2000/N736Fall2017_lesson07/raw/master/lesson07_Rcode.R)
    
* `SAS` Programs
    - SAS Programs to load HELP dataset - formatting [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sas](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/helpmkh.sas)
    - SAS Programs to load HELP dataset - load [https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/loadHELPdata.sas](https://github.com/melindahiggins2000/N736Fall2017_HELPdataset/raw/master/loadHELPdata.sas)
    - SAS Program to begin univariate analyses [https://github.com/melindahiggins2000/N736Fall2017_lesson07/raw/master/lesson07_SAScode.sas](https://github.com/melindahiggins2000/N736Fall2017_lesson07/raw/master/lesson07_SAScode.sas)
    
    
